### ISSUE TITLE
"Show password" feature: allow user to view the password he entered

### ISSUE THREAD

**Issue by yann-yinn** [yann-yinn/adonis-starter#16]
a little blue link "show password" above the password field, for example (this is form from mailchimp)

<img width="443" alt="Capture d’écran 2021-09-29 à 18 21 58" src="https://user-images.githubusercontent.com/335495/135309360-6693bb6e-0446-4fc4-bb58-c644cdbe93a1.png">

This must work on the following forms:

- register
- login
- reset password

**Comment by Sreejit7** [comment]
hey, could you please direct me to the file where this form is located?

**Comment by yann-yinn** [comment]
@Sreejit7 several places for now:

https://github.com/yann-yinn/mvp-starter/blob/main/resources/views/forms/signupForm.edge
https://github.com/yann-yinn/mvp-starter/blob/main/resources/views/forms/userForm.edge
https://github.com/yann-yinn/mvp-starter/blob/main/resources/views/forms/signinForm.edge
https://github.com/yann-yinn/mvp-starter/blob/main/resources/views/pages/resetPassword.edge

**Comment by yann-yinn** [comment]
PS: form picture in the first comment of this issue is just an example from mailchimp site

**Comment by Sreejit7** [comment]
Thanks! Do you want to the default behavior of passwords to be hidden or visible?

**Comment by yann-yinn** [comment]
you're welcome ! Hidden by default

**Comment by Sreejit7** [comment]
Got it. I would like to try this, would you please assign this to me?

**Comment by yann-yinn** [comment]
maybe it's time to consider moving password fields to their own component / partial to avoid dupplicated code, feel free to suggest what you think is the best :)

**Comment by Sreejit7** [comment]
yeah sure :)

**Comment by Sreejit7** [comment]
Do I need to setup SMTP in SES for running the project? facing some error in running with regards to SMTP variables

**Comment by yann-yinn** [comment]
yep we are sending mail on account creation / forgot password, so you need to configure a STMP. I'm using "send in blue" in France but maybe you can create a "mailgun" account for example ?

**Comment by yann-yinn** [comment]
PS: or SES (this is aws solution isn't it ?), never used it so i don't know if they are providing SMTP or an API

**Comment by Sreejit7** [comment]
Thanks, I'll check it out. I've never used SES as well, but saw some SES related stuff in the .env file too, that's why I thought it might be needed.

**Comment by yann-yinn** [comment]
Oh I see, in the .env.example yes. 

For now `config/mail.ts` is configured to "smtp" by default, so actually for now only those variables are used:

```
SMTP_HOST=<localhost>
SMTP_PORT=587
SMTP_USERNAME=<username>
SMTP_PASSWORD=<password>
```

**Comment by Sreejit7** [comment]
I figured it out, it runs now! Thanks!

**Comment by Sreejit7** [comment]
@yann-yinn I've added a solution that works for now, but the code is a lil ugly. I'll try to improve on it!

**Comment by yann-yinn** [comment]
merged !
